spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/linhs_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

# 1. Explicitly tell Spring to use the PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Explicitly tell Hibernate to use the PostgreSQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update