spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/linhs_portal}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB