# Database Configuration using Environment Variables
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Keep your file upload configurations safely separated
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB